name: movie_online
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5

  #dio
  dio: ^4.0.6

  flutter_soap: ^2.0.0

  url_launcher: ^6.0.6

  pretty_dio_logger: ^1.1.1

  #shared pref
  shared_preferences: ^2.0.15

  #connectivity
  connectivity: ^3.0.6

  #toast
  fluttertoast: ^8.0.9

  #intl
  intl: ^0.17.0

  #image
  cached_network_image: ^3.2.3

  path_provider: ^2.0.0
  path: ^1.8.1

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
